[toolchain]
anchor-version = "0.30.1"
solana-version = "1.18"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/dev.json"

[programs.devnet]
bastion_audit = "A29V5MUVs73y7XBHHxPpPcAW7h4gGHupbDdwYSwA2n9D"

[scripts]
test = "cargo test --features devnet"
build = "cargo build --features devnet"